---
driver:
  name: vagrant
driver_config:
  http_proxy: http://webproxysea.nordstrom.net:8181
  https_proxy: http://webproxysea.nordstrom.net:8181

provisioner:
  name: chef_zero

platforms:
  - name: updaterhel5-update
    attributes:
      unix_chef_client_upgrade:
        kill_after_install: false
    driver_config:
      box: nordrhel5
      box_url: http://y0319p297/downloads/rhel5_virtualbox.box
      require_chef_omnibus: 11.12.0
  - name: updaterhel6-current
    driver_config:
      box: nordrhel64
      box_url: http://y0319p297/downloads/rhel6_virtualbox.box
      require_chef_omnibus: 11.12.8
  - name: updaterhel6-ahead
    driver_config:
      box: nordrhel64
      box_url: http://y0319p297/downloads/rhel6_virtualbox.box
      require_chef_omnibus: 11.16.0
  - name: updaterhel6-update
    attributes:
      unix_chef_client_upgrade:
        kill_after_install: false
    driver_config:
      box: nordrhel64
      box_url: http://y0319p297/downloads/rhel6_virtualbox.box
      require_chef_omnibus: 11.12.0
  - name: updatesol10-update
    attributes:
      unix_chef_client_upgrade:
        kill_after_install: false
    driver_config:
      box: nordsol10
      box_url: http://y0319p297.nordstrom.net/downloads/vagrant-solaris10.box
      require_chef_omnibus: 11.12.0
  - name: updatesol11-update
    attributes:
      unix_chef_client_upgrade:
        kill_after_install: false
    driver_config:
      box: nordsol11
      box_url: http://y0319p297.nordstrom.net/downloads/vagrant-solaris11.box
      require_chef_omnibus: 11.12.8

suites:
  - name: default
    run_list:
      - recipe[rhn_satellite::default]
      - recipe[unix_chef_client_upgrade::default]
    attributes:
