name             'unix_chef_client_upgrade'
maintainer       'Nordstrom, Inc.'
maintainer_email 'CHANGE_ME_TO_SOMETHING_APPROPRIATE@nordstrom.com'
license          'All rights reserved'
description      'Installs/Configures unix_chef_client_upgrade'
long_description 'Longer version of description: Installs/Configures unix_chef_client_upgrade'
version          '0.0.0'
