default["chef-client-upgrade"]["url"]          = "com/opscode/chef/chef-client"
default["chef-client-upgrade"]["msi_checksum"] = "c85e1606ce20eb5008e91b0dd218f325600567b18c453c1eeea71aba241d3566"
default["chef-client-upgrade"]["version"]      = "11.4.0-1"
default["chef-client-upgrade"]["display_name"] = "Opscode Chef Client Installer for Windows v11.4.0"
default["chef-client-upgrade"]["pkg_name"]     = "chef"
default["chef-client-upgrade"]["ohai_chef_vs"] = "11.4.0"
default["chef-client-upgrade"]["pkg_path"]     = "/opt/admin/software/chef/client-install-11.4.0/"
default["chef-client-upgrade"]["nocheck"]      = "/var/sadm/install/admin/nocheck"